# .github/workflows/deploy.yml
name: Build and Deploy

# Trigger on push to main branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent concurrent deployments
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build website
      run: npm run build

    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload build folder
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4