# .github/workflows/deploy.yml
name: Build and Deploy

# Trigger on push to main branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Configure Git
      run: |
        git config --global user.name "Subhajit Baidya"
        git config --global user.email "subhajitbaidya43@gmail.com"

    - name: Build and Deploy
      run: |
        npm run build
        npx gh-pages -d dist
     